set_project("SkyrimTextBridge")
set_version("0.3.6")
set_languages("cxx23")
set_config("skyrim_se", true)
set_config("skyrim_ae", true)
set_config("skyrim_vr", false)
set_config("tests", false)
add_rules("mode.debug", "mode.release", "mode.releasedbg")
includes("extern/CommonLibVR")

target("SkyrimTextBridge")
    set_kind("shared")
    add_files("src/*.cpp")
    remove_files("src/Composer.cpp")
    add_includedirs("include", "extern/PrismaUI")
    add_deps("commonlibsse-ng")
    add_defines("TEXTBRIDGE_MANUAL_BUILD", "NOMINMAX", "WIN32_LEAN_AND_MEAN", "UNICODE", "_UNICODE")
    add_syslinks("user32", "gdi32", "imm32", "comctl32", "ole32", "oleaut32", "uuid")

target("BridgeCoreTests")
    set_kind("binary")
    set_default(false)
    add_files("tests/CoreTests.cpp")
    add_includedirs("include")
