const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('assets/MeridianBridge.js','utf8').replace(/^\uFEFF/,'');
let calls=[],status=[],listeners={};
const field={tagName:'INPUT',type:'search',disabled:false,readOnly:false};
const doc={activeElement:field,documentElement:{contains:e=>e===field},execCommand:(cmd,show,text)=>{calls.push([cmd,text]);return true;}};
const window={stbMeridianResult:s=>status.push(s),addEventListener:(event,callback)=>listeners[event]=callback};
const context=vm.createContext({document:doc,window});
vm.runInContext(source,context);const api=window.__stbMeridian;
api.capture(1);assert.equal(status.at(-1),'1:ready');
api.commit(1,'中文');assert.deepEqual(calls.pop(),['insertText','中文']);
api.commit(1,'\";window.attack=1;//😀');assert.equal(window.attack,undefined);assert.equal(calls.pop()[1],'\";window.attack=1;//😀');
api.commit(0,'old');assert.equal(status.at(-1),'0:stale-field');
const other={...field};doc.activeElement=other;api.commit(1,'wrong');assert.equal(calls.length,0);
doc.activeElement=field;field.readOnly=true;api.commit(1,'readonly');assert.equal(calls.length,0);field.readOnly=false;
field.type='password';api.capture(2);assert.equal(status.at(-1),'2:no-field');field.type='search';
api.capture(3);api.cancel(2);api.commit(3,'有效');assert.equal(calls.pop()[1],'有效');
api.cancel(3);api.commit(3,'cancelled');assert.equal(calls.length,0);
api.capture(4);listeners.blur();api.commit(4,'blur');assert.equal(calls.length,0);
const iframe={tagName:'IFRAME',contentDocument:doc};const outer={activeElement:iframe};context.document=outer;
api.capture(5);api.commit(5,'iframe');assert.equal(calls.pop()[1],'iframe');
doc.execCommand=()=>false;api.commit(5,'reject');assert.equal(status.at(-1),'5:insert-rejected');
vm.runInContext(source,context);assert.equal(window.__stbMeridian,api);
console.log('Meridian DOM checks passed: Unicode, literal text, stale field/session, readonly/password, cancel, blur, iframe and insertion failure');
